### ISSUE TITLE
Can't use config.yml with Docker

### ISSUE THREAD

**Issue by bilyboy785** [soyuka/explorer#40]
I mount my config.yml in the docker-compose file but Explorer don't use it ... How can i do ?

```
explorer:
    restart: always
    container_name: explorer
    image: explorer
    volumes:
      - /home/user/dockers/explorer/docker/config/config.yml:/opt/explorer
      - /home/user/dockers/explorer/docker/config/users:/users
      - /home/user/dockers/explorer/docker/data/archive:/archive
      - /home/user/dockers/explorer/docker/data/trash:/trash
      - /home/user/dockers/explorer/docker/data/upload:/upload
      - /home/user/data:/data
    ports:
      - 7745:4859
    environment:
      - VIRTUAL_HOST=domain.tld
      - LETSENCRYPT_HOST=domain.tld
      - LETSENCRYPT_EMAIL=contact@domain.tld
```
